#######################
## foodweb_builder.R ##
#######################

## Goal: functions file for building local foodwebs

###############
## FUNCTIONS ##
###############

#' Build a Local Food Web from a Global Metaweb
#'
#' @description
#' Extracts a local food web (subnetwork) from a global metaweb based on the
#' species and individual sizes observed at a specific site or sample. The
#' function filters the metaweb to include only the trophic species and
#' resources present locally.
#'
#' @param ind_measure_local A data frame of local individual‐level
#'   measurements containing the columns `species_code` and `size`.
#'   Each row represents an observed individual in the local community.
#' @param metaweb A global metaweb adjacency matrix (as produced by
#'   [build_metaweb()]) representing all potential interactions among
#'   trophic species and resources.
#' @param tab_size_classes A data frame of size‐class boundaries for each
#'   species, typically generated by [compute_size_classes()]. Must include
#'   a `species_code` column and class bounds.
#' @param num_classes Integer indicating the number of size classes per
#'   species, matching the value used in [build_metaweb()].
#' @param selected_resources Character vector giving the names of resource
#'   nodes to retain in the local network.
#'
#' @return
#' A square adjacency matrix (data frame or matrix) representing the subset
#' of the metaweb that corresponds to locally present trophic species and
#' resources.
#'
#' @details
#' For each individual observed locally, the function determines which
#' trophic species (species–size‐class combinations) are represented based
#' on body size. It then filters the global metaweb to include only those
#' trophic species and the selected resource nodes, yielding a local‐scale
#' interaction network.
#'
#' @examples
#' \dontrun{
#' local_fw <- build_local_foodweb(
#'   ind_measure_local = local_measurements,
#'   metaweb = global_metaweb,
#'   tab_size_classes = size_classes,
#'   num_classes = 5,
#'   selected_resources = c("zooplankton", "benthos")
#' )
#' dim(local_fw)
#' }
#'
#' @seealso [build_metaweb()], [compute_size_classes()]
#'
#' @export
build_local_foodweb = function(ind_measure_local, metaweb, tab_size_classes, num_classes, selected_resources){
  
  ## Flatten
  trophic_species_code = paste(rep(tab_size_classes[,1], 1, each=num_classes), 1:num_classes, sep="_")
  lb_size_classes = as.numeric(t(as.matrix(tab_size_classes[,-c(1,ncol(tab_size_classes))])))
  ub_size_classes = as.numeric(t(as.matrix(tab_size_classes[,-c(1,2)])))
  
  ## Check presence
  check = NULL
  for (i in 1:nrow(ind_measure_local)){
    
    ## Check presence
    check_ = (
      grepl(pattern = ind_measure_local$species_code[i], x = trophic_species_code) &
        (ind_measure_local$size[i] >= lb_size_classes) &
        (ind_measure_local$size[i] < ub_size_classes)
    )*1
    
    ## Collect
    check = rbind(check, check_)
  }
  
  ## Collapse
  check = apply(check, 2, sum)
  cbind(trophic_species_code, check)
  
  ## Subset
  s = which(check > 0)
  trophic_species_code_subset = c(trophic_species_code[s], selected_resources)
  
  ## Subset metaweb
  metaweb_ = metaweb[trophic_species_code_subset, trophic_species_code_subset]
  
  ## End
  return(metaweb_)
  
}

#
###









































