#######################
## foodweb_builder.R ##
#######################

## Goal: functions file for building local food webs

###############
## FUNCTIONS ##
###############

#' Build a Local Food Web from a Global Metaweb for All Local Units
#'
#' @description
#' Builds a local food web (subnetwork) from a global metaweb **for each**
#' local sampling unit present in `ind_measure`, as defined by the column
#' given in `local_id`.
#'
#' For each local unit, the function identifies which trophic species
#' (species–size‐class combinations) are represented locally based on
#' individual sizes, then subsets the global metaweb accordingly.
#'
#' @param ind_measure A data frame of individual-level measurements containing
#'   at least the columns specified by `local_id`, `species_code`, and `size`.
#'   Each row represents an observed individual in the local community.
#' @param local_id A character string giving the name of the column in
#'   `ind_measure` that defines the local sampling units (e.g. `"site_id"`,
#'   `"operation_id"`).
#' @param metaweb A global metaweb adjacency matrix (as produced by
#'   [build_metaweb()]) representing all potential interactions among
#'   trophic species and resources.
#' @param tab_size_classes A data frame of size‐class boundaries for each
#'   species, typically generated by [compute_size_classes()]. Must include
#'   a `species_code` column and class bounds.
#' @param num_classes Integer indicating the number of size classes per
#'   species, matching the value used in [build_metaweb()].
#' @param selected_resources Character vector of resource nodes to keep in each
#'   local food web.
#'
#' @return
#' A named list of local food webs.
#' Each element is a square adjacency matrix, and names correspond to unique
#' values of `ind_measure[[local_id]]`.
#'
#' @details
#' For each local unit, the function:
#' 1. Extracts the individuals belonging to that unit.
#' 2. Determines the represented trophic species using size-class boundaries.
#' 3. Subsets the metaweb to keep only present trophic species + resources.
#'
#' @examples
#' \dontrun{
#' # Minimal reproducible example :
#'
#' # Suppose you already built:
#' #  - a global metaweb object named `metaweb`
#' #  - a table of size classes named `size_classes`
#' #  - an individual measurement table `ind_measure`
#'
#' local_foodwebs <- build_local_foodweb(
#'   ind_measure      = ind_measure,
#'   local_id         = "operation_id",
#'   metaweb          = metaweb,
#'   tab_size_classes = size_classes,
#'   num_classes      = 5,
#'   selected_resources = c("zoopl", "phytopl")
#' )
#'
#' names(local_foodwebs)
#' dim(local_foodwebs[[1]])
#' }
#'
#' @seealso [build_metaweb()], [compute_size_classes()]
#'
#' @export
build_local_foodweb <- function(ind_measure,
                                local_id,
                                metaweb,
                                tab_size_classes,
                                num_classes,
                                selected_resources) {

  ## 1. Check required columns are present in ind_measure
  required_cols <- c(local_id, "species_code", "size")
  missing_cols  <- setdiff(required_cols, colnames(ind_measure))

  if (length(missing_cols) > 0) {
    stop(
      "ind_measure must contain the following columns: ",
      paste(missing_cols, collapse = ", "),
      call. = FALSE
    )
  }

  ## 2. Build trophic species codes (species × size class)
  trophic_species <- paste(
    rep(tab_size_classes[, 1], each = num_classes),
    1:num_classes,
    sep = "_"
  )

  ## 3. Flatten lower / upper bounds for size classes
  # These vectors are aligned with 'trophic_species'
  lb <- as.numeric(
    t(as.matrix(tab_size_classes[, -c(1, ncol(tab_size_classes))]))
  )
  ub <- as.numeric(
    t(as.matrix(tab_size_classes[, -c(1, 2)]))
  )

  ## 4. Extract species code for each trophic species
  species_of_ts <- sub("_.*$", "", trophic_species)

  # Pre-compute, for each species_code, the indices of its trophic species
  species_index <- split(seq_along(trophic_species), species_of_ts)

  ## 5. Identify all unique local units
  local_units <- unique(ind_measure[[local_id]])

  ## 6. Internal helper: build local web for one unit
  build_one_local <- function(df_local) {

    n_ind <- nrow(df_local)
    n_ts  <- length(trophic_species)

    # Logical vector: which trophic species are present locally?
    present <- logical(n_ts)

    for (i in seq_len(n_ind)) {

      sp     <- df_local$species_code[i]
      size_i <- df_local$size[i]

      # Indices of trophic species associated with this species code
      idx <- species_index[[sp]]

      if (length(idx) == 0L) next

      # Among those trophic species, which classes contain this individual size?
      in_class <- (size_i >= lb[idx]) & (size_i < ub[idx])

      # Mark these trophic species as present
      present[idx[in_class]] <- TRUE
    }

    # Keep locally present trophic species + selected resource nodes
    keep <- c(trophic_species[present], selected_resources)

    # Subset the global metaweb to obtain the local food web
    metaweb[keep, keep, drop = FALSE]
  }

  ## 7. Build local food webs for each local unit
  results <- lapply(local_units, function(id) {
    subset_local <- ind_measure[ind_measure[[local_id]] == id,
                                c("species_code", "size")]
    build_one_local(subset_local)
  })

  # Name list elements with the local_id values
  names(results) <- as.character(local_units)

  return(results)
}
